"theme:workflow":
  - ".github/**"

"theme:build":
  - "gradle/**"
  - "build.gradle.kts"
  - "**/build.gradle.kts"
  - "gradle.properties"
  - ".gitignore"

"theme:assertj":
  - "allure-assertj/**"

"theme:awaitility":
  - "allure-awaitility/**"

"theme:bom":
  - "allure-bom/**"

"theme:citrus":
  - "allure-citrus/**"

"theme:cucumber-jvm":
  - "allure-cucumber7-jvm/**"

"theme:descriptions-javadoc":
  - "allure-descriptions-javadoc/**"

"theme:grpc":
  - "allure-grpc/**"

"theme:hamcrest":
  - "allure-hamcrest/**"

"theme:httpclient":
  - "allure-httpclient/**"
  - "allure-httpclient5/**"

"theme:model":
  - "allure-model/**"

"theme:core":
  - "allure-java-commons/**"
  - "allure-java-commons-test/**"

"theme:jax-rs":
  - "allure-jax-rs/**"

"theme:jbehave":
  - "allure-jbehave5/**"

"theme:jooq":
  - "allure-jooq/**"

"theme:jsonunit":
  - "allure-jsonunit/**"

"theme:junit4":
  - "allure-junit4/**"
  - "allure-junit4-aspect/**"

"theme:junit-platform":
  - "allure-jupiter/**"
  - "allure-jupiter-assert/**"
  - "allure-junit-platform/**"

"theme:karate":
  - "allure-karate/**"

"theme:okhttp":
  - "allure-okhttp3/**"

"theme:playwright":
  - "allure-playwright/**"

"theme:rest-assured":
  - "allure-rest-assured/**"

"theme:scalatest":
  - "allure-scalatest/**"

"theme:selenium-bidi":
  - "allure-selenium-bidi/**"

"theme:selenide":
  - "allure-selenide/**"

"theme:servlet-api":
  - "allure-servlet-api/**"

"theme:spock":
  - "allure-spock2/**"

"theme:spring":
  - "allure-spring-web/**"

"theme:testng":
  - "allure-testng/**"
