/*
 *  Copyright 2016-2026 Qameta Software Inc
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package io.qameta.allure.awaitility;

import io.qameta.allure.Description;
import io.qameta.allure.model.Status;
import io.qameta.allure.model.StepResult;
import io.qameta.allure.model.TestResult;
import io.qameta.allure.test.IsolatedLifecycle;
import org.awaitility.Awaitility;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import static io.qameta.allure.test.RunUtils.runWithinTestContext;
import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

@TestInstance(TestInstance.Lifecycle.PER_METHOD)
@IsolatedLifecycle
class GlobalSettingsPositiveTest {

    private static final String AWAITILITY_EVALUATION_DESCRIPTION = "Awaitility condition satisfied or not, but awaiting still in progress";

    @AfterEach
    void reset() {
        Awaitility.reset();
    }

    @BeforeEach
    void setup() {
        Awaitility.pollInSameThread();
        Awaitility.setDefaultConditionEvaluationListener(new AllureAwaitilityListener());
    }

    /**
     * Verifies that a successful Awaitility condition using the global Allure listener is reported as one top-level step
     * when no await alias is provided.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldCreateSingleTopLevelStep() {
        final List<StepResult> steps = runAwaitWithoutAliasTopLevelSteps();

        assertThat(steps)
                .as("Exactly 1 top level step for 1 awaitility condition")
                .hasSize(1);
    }

    /**
     * Verifies that the top-level report step created by the global Awaitility listener is marked passed for a
     * successful condition.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldMarkTopLevelStepPassed() {
        final StepResult step = awaitWithoutAliasTopLevelStep();

        assertThat(step.getStatus())
                .as("Top level step has passed status")
                .isEqualTo(Status.PASSED);
    }

    /**
     * Verifies that a successful globally-listened Awaitility condition without an alias keeps the default top-level
     * step name in the report.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldUseDefaultTopLevelStepName() {
        final StepResult step = awaitWithoutAliasTopLevelStep();

        assertThat(step.getName())
                .as("Top level step has default name because await() wo alias")
                .isEqualTo("Awaitility: Starting evaluation");
    }

    /**
     * Verifies that an Awaitility alias is preserved in the top-level report step when the listener is configured
     * globally.
     */
    @Description
    @Test
    void globalSettingsAwaitWithAliasCheckTopLevelPassedStep() {
        final StepResult step = awaitWithAliasTopLevelStep();

        assertThat(step.getName())
                .as("Top level step has name with alias")
                .isEqualTo("Awaitility: Counter should be at least 3");
    }

    /**
     * Verifies that the global Awaitility listener creates one condition-evaluation child report step for each poll
     * before a successful condition completes.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldCreateSecondLevelStepForEachPoll() {
        final List<StepResult> steps = awaitWithoutAliasPollSteps();

        assertThat(steps)
                .as("Exactly 4 second level steps for 4 polling iterations")
                .hasSize(4);
    }

    /**
     * Verifies that every poll-level report step generated by the global listener is passed for a successful condition.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldMarkAllSecondLevelStepsPassed() {
        final List<StepResult> steps = awaitWithoutAliasPollSteps();

        assertThat(steps)
                .extracting(StepResult::getStatus)
                .containsExactlyInAnyOrder(
                        Status.PASSED,
                        Status.PASSED,
                        Status.PASSED,
                        Status.PASSED
                );
    }

    /**
     * Verifies that the first failed poll from the global listener reports the evaluated condition, expected and actual
     * values, and timing context.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldDescribeFirstFailedPoll() {
        final StepResult step = firstFailedPollStep();

        assertThat(step.getName())
                .contains("io.qameta.allure.awaitility.GlobalSettingsPositiveTest")
                .contains("expected: 3")
                .contains("but was: 0")
                .contains("elapsed time")
                .contains("remaining time")
                .contains("last poll interval was");
    }

    /**
     * Verifies that the second failed poll from the global listener reports the next observed value with timing context.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldDescribeSecondFailedPoll() {
        final StepResult step = secondFailedPollStep();

        assertThat(step.getName())
                .contains("io.qameta.allure.awaitility.GlobalSettingsPositiveTest")
                .contains("expected: 3")
                .contains("but was: 1")
                .contains("elapsed time")
                .contains("remaining time")
                .contains("last poll interval was");
    }

    /**
     * Verifies that the third failed poll from the global listener reports the final unsuccessful value before success.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldDescribeThirdFailedPoll() {
        final StepResult step = thirdFailedPollStep();

        assertThat(step.getName())
                .contains("io.qameta.allure.awaitility.GlobalSettingsPositiveTest")
                .contains("expected: 3")
                .contains("but was: 2")
                .contains("elapsed time")
                .contains("remaining time")
                .contains("last poll interval was");
    }

    /**
     * Verifies that the successful poll from the global listener reports the reached value and timing context.
     */
    @Description
    @Test
    void awaitWithoutAliasShouldDescribeSuccessfulPoll() {
        final StepResult step = successfulPollStep();

        assertThat(step.getName())
                .contains("io.qameta.allure.awaitility.GlobalSettingsPositiveTest")
                .contains("reached its end value after")
                .contains("remaining time")
                .contains("last poll interval was");
    }

    private List<StepResult> runAwaitWithoutAliasTopLevelSteps() {
        final List<TestResult> testResult = runWithinTestContext(() -> {
            final AtomicInteger atomicInteger = new AtomicInteger(0);
            await().with()
                    .atMost(Duration.of(1000, ChronoUnit.MILLIS))
                    .pollInterval(Duration.of(50, ChronoUnit.MILLIS))
                    .untilAsserted(() -> assertThat(atomicInteger.getAndIncrement()).isEqualTo(3));
        }).getTestResults();

        return testResult.get(0).getSteps();
    }

    private StepResult awaitWithoutAliasTopLevelStep() {
        return runAwaitWithoutAliasTopLevelSteps().get(0);
    }

    private StepResult awaitWithAliasTopLevelStep() {
        final List<TestResult> testResult = runWithinTestContext(() -> {
            final AtomicInteger atomicInteger = new AtomicInteger(0);
            await("Counter should be at least 3").with()
                    .atMost(Duration.of(1000, ChronoUnit.MILLIS))
                    .pollInterval(Duration.of(50, ChronoUnit.MILLIS))
                    .untilAsserted(() -> assertThat(atomicInteger.getAndIncrement()).isEqualTo(3));
        }).getTestResults();

        return testResult.get(0).getSteps().get(0);
    }

    private List<StepResult> awaitWithoutAliasPollSteps() {
        return awaitWithoutAliasTopLevelStep().getSteps().stream()
                .filter(GlobalSettingsPositiveTest::isAwaitilityEvaluationStep)
                .toList();
    }

    private static boolean isAwaitilityEvaluationStep(final StepResult step) {
        return AWAITILITY_EVALUATION_DESCRIPTION.equals(step.getDescription());
    }

    private StepResult firstFailedPollStep() {
        return awaitWithoutAliasPollSteps().get(0);
    }

    private StepResult secondFailedPollStep() {
        return awaitWithoutAliasPollSteps().get(1);
    }

    private StepResult thirdFailedPollStep() {
        return awaitWithoutAliasPollSteps().get(2);
    }

    private StepResult successfulPollStep() {
        return awaitWithoutAliasPollSteps().get(3);
    }

}
