name: "Verify type labels"

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  contents: read 

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: baev/action-label-verify@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed: |
            type:bug
            type:dependencies
            type:improvement
            type:internal
            type:invalid
            type:new feature
            type:security
            type:documentation
